version: '3.4'

services:

  tendermint_node:
    image: ${TENDERMINT_NODE_IMAGE}
    container_name: ${SOLO_NODE_CONTAINER}
    working_dir: /root
    command: sh ./provision.sh
    ports:
      - "26656-26657:26656-26657"
    volumes:
      - ./provision.sh:/root/provision.sh
    networks:
      - local

networks: 
  local:
      name: ${SOLO_NETWORK}