version: '3.4'

services:

  node0:
    image: ${TMINT_LOCAL_IMAGE}
    container_name: node0
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=tendermint.log
    networks:
      local:
        ipv4_address: 192.167.0.2

  node1:
    image: ${TMINT_LOCAL_IMAGE}
    container_name: node1
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=tendermint.log
    networks:
      local:
        ipv4_address: 192.167.0.3
  node2:
    image: ${TMINT_LOCAL_IMAGE}
    container_name: node2
    ports:
      - "26661-26662:26656-26657"
    environment:
      - ID=2
      - LOG=tendermint.log
    networks:
      local:
        ipv4_address: 192.167.0.4

  node3:
    image: ${TMINT_LOCAL_IMAGE}
    container_name: node3
    ports:
      - "26663-26664:26656-26657"
    environment:
      - ID=3
      - LOG=tendermint.log
    networks:
      local:
        ipv4_address: 192.167.0.5

networks: 
  local:
    name: ${TMINT_EX1_NETWORK}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.0.0/16