version: '3.4'

services:

  admin:
    image: ${TMINT_BASE_IMAGE}
    container_name: admin
    command: tendermint testnet --o /etc/tendermint --starting-ip-address 192.168.0.2
    volumes:
      - vol:/etc/tendermint

  node0:
    image: ${TMINT_LOCAL_IMAGE}
    container_name: node0
    command: node --home=/etc/tendermint/node0 --proxy_app=kvstore
    ports:
      - "26656-26657:26656-26657"
    volumes:
      - vol:/etc/tendermint
    networks:
      local:
        ipv4_address: 192.168.0.2
    depends_on:
      - admin

  node1:
    image: ${TMINT_LOCAL_IMAGE}
    container_name: node1
    command: node --home=/etc/tendermint/node1 --proxy_app=kvstore
    ports:
      - "26659-26660:26656-26657"
    volumes:
      - vol:/etc/tendermint
    networks:
      local:
        ipv4_address: 192.168.0.3
    depends_on:
      - admin

  node2:
    image: ${TMINT_LOCAL_IMAGE}
    container_name: node2
    command: node --home=/etc/tendermint/node2 --proxy_app=kvstore
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - vol:/etc/tendermint
    networks:
      local:
        ipv4_address: 192.168.0.4
    depends_on:
      - admin

  node3:
    image: ${TMINT_LOCAL_IMAGE}
    container_name: node3
    command: node --home=/etc/tendermint/node3 --proxy_app=kvstore 
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - vol:/etc/tendermint
    networks:
      local:
        ipv4_address: 192.168.0.5
    depends_on:
      - admin

networks: 
  local:
    name: ${TMINT_EX1_NETWORK}
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16
          ip_range: 192.168.0.0/24
          gateway: 192.168.0.254

volumes:
  vol:
    name: ${TMINT_CLUSTER_VOL}
